version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  static_files_data:
    external: true
  media_files_data:
    external: true

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: trivianator_production_django
    environment:
      DJANGO_SELF_HOST: ${DJANGO_SELF_HOST}
    volumes:
      - static_files_data:/app/staticfiles
      - media_files_data:/app/mediafiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "8000:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: trivianator_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

 # apache:
 #  build:
 #    context: .
 #    dockerfile: ./compose/production/apache2/Dockerfile
 #  image: trivianator_production_apache
 #  container_name: apache
 #  environment:
 #    DJANGO_UPSTREAM_SERVER: ${DJANGO_SELF_HOST}
 #    DJANGO_UPSTREAM_PORT: ${DJANGO_UPSTREAM_PORT:-8000}
 #    DJANGO_SELF_HOST: ${DJANGO_SELF_HOST}
 #  volumes:
 #    - static_files_data:/opt/staticfiles
 #    - media_files_data:/opt/mediafiles
 #  ports:
 #    - "8090:80"
 #   depends_on:
 #      - django
 #
 # nginx:
 #  build:
 #    context: .
 #    dockerfile: ./compose/production/nginx/Dockerfile
 #  image: trivianator_production_nginx
 #  container_name: nginx
 #  environment:
 #    DJANGO_UPSTREAM_SERVER: ${DJANGO_SELF_HOST}
 #    DJANGO_UPSTREAM_PORT: ${DJANGO_UPSTREAM_PORT:-8000}
 #    DJANGO_SELF_HOST: ${DJANGO_SELF_HOST}
 #  volumes:
 #    - static_files_data:/opt/staticfiles
 #    - media_files_data:/opt/mediafiles
 #  ports:
 #    - "8080:80"
 #  depends_on:
 #    - django

  # traefik:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/traefik/Dockerfile
  #   image: trivianator_production_traefik
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_traefik:/etc/traefik/acme
  #   ports:
  #     - "0.0.0.0:80:80"
  #     - "0.0.0.0:443:443"
  #     - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  # celeryworker:
  #   <<: *django
  #   image: trivianator_production_celeryworker
  #   command: /start-celeryworker
  #   ports: []
  #
  # celerybeat:
  #   <<: *django
  #   image: trivianator_production_celerybeat
  #   command: /start-celerybeat
  #   ports: []
  #
  # flower:
  #   <<: *django
  #   image: trivianator_production_flower
  #   command: /start-flower
  #   ports:
  #     - "5555:5555"
